-- SQLBook: Code
-- Creation des tables
-- Table Abonnement
CREATE TABLE Abonnement (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL
);

-- Table Genre
CREATE TABLE Genre (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL
);

-- Table Type
CREATE TABLE Type (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL
);

-- Table ProfilPicture
CREATE TABLE ProfilPicture (
  id INT PRIMARY KEY AUTO_INCREMENT,
  profil_picture TEXT
);

-- Table Users (user est réservé, donc on peut nommer users)
CREATE TABLE Users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  firstname VARCHAR(150) NOT NULL,
  lastname VARCHAR(150) NOT NULL,
  mail VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(150) NOT NULL,
  is_admin BOOLEAN NOT NULL DEFAULT FALSE,
  is_actif BOOLEAN NOT NULL DEFAULT TRUE,
  abonnement_id INT NOT NULL,
  profil_picture_id INT DEFAULT 1,
  FOREIGN KEY (abonnement_id) REFERENCES Abonnement(id),
  FOREIGN KEY (profil_picture_id) REFERENCES ProfilPicture(id)
);

-- Table Anime
CREATE TABLE Anime (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  synopsis TEXT,
  portrait TEXT,
  date YEAR,
  genre_id INT NOT NULL,
  paysage TEXT,
  video TEXT,
  FOREIGN KEY (genre_id) REFERENCES Genre(id) ON DELETE RESTRICT
);

-- Table Note
CREATE TABLE Note (
id INT PRIMARY KEY AUTO_INCREMENT,
users_id INT NOT NULL,
anime_id INT NOT NULL, 
note INT CHECK (note BETWEEN 0 AND 5),
FOREIGN KEY (users_id) REFERENCES Users(id) ON DELETE CASCADE,
FOREIGN KEY (anime_id) REFERENCES Anime(id) ON DELETE CASCADE
);

-- Table Season
CREATE TABLE Season (
  id INT PRIMARY KEY AUTO_INCREMENT,
  number INT NOT NULL,
  anime_id INT NOT NULL,
  FOREIGN KEY (anime_id) REFERENCES Anime(id) ON DELETE CASCADE
);

-- Table Episode
CREATE TABLE Episode (
  id INT PRIMARY KEY AUTO_INCREMENT,
  number INT NOT NULL,
  title VARCHAR(150) NOT NULL,
  synopsis TEXT,
  season_id INT NOT NULL,
  FOREIGN KEY (season_id) REFERENCES Season(id) ON DELETE CASCADE
);

-- Table Anime_type
CREATE TABLE Anime_type (
  id INT PRIMARY KEY AUTO_INCREMENT,
  type_id INT NOT NULL,
  anime_id INT NOT NULL,
  FOREIGN KEY (type_id) REFERENCES Type(id) ON DELETE RESTRICT,
  FOREIGN KEY (anime_id) REFERENCES Anime(id) ON DELETE CASCADE
);

-- Table users_anime
CREATE TABLE users_anime (
  id INT PRIMARY KEY AUTO_INCREMENT,
  anime_id INT NOT NULL,
  users_id INT NOT NULL,
  UNIQUE (users_id, anime_id),
  FOREIGN KEY (users_id) REFERENCES Users(id) ON DELETE CASCADE,
  FOREIGN KEY (anime_id) REFERENCES Anime(id) ON DELETE CASCADE
);

-- Table favorite_anime
CREATE TABLE favorite_anime(
  id INT PRIMARY KEY AUTO_INCREMENT,
  anime_id INT NOT NULL,
  users_id INT NOT NULL,
  FOREIGN KEY (users_id) REFERENCES Users(id) ON DELETE CASCADE,
  FOREIGN KEY (anime_id) REFERENCES Anime(id) ON DELETE CASCADE
);

-- Requêtes d'insertion
-- Insertion des abonnements
INSERT INTO Abonnement (name) VALUES
('Découverte'),
('Premium');

-- Insertion des genres
INSERT INTO Genre (name) VALUES
('Shonen'),
('Seinen'),
('Shojo');

-- Insertion des types
INSERT INTO Type (name) VALUES
('Fantasy'),
('Dark-Fantasy'),
('Combat'),
('Drame'),
('Humour'),
('Amour'),
('Comédie'),
('Tranche de vie'),
('Thriller');

-- Insertion des images de profil
INSERT INTO ProfilPicture (profil_picture) VALUES
('https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/profilpicture/404.png'),
('https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/profilpicture/connectedavatar.svg'),
('https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/profilpicture/profilpicture.png'),
('https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/profilpicture/profilpicture2.png'),
('https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/profilpicture/profilpicture3.png'),
('https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/profilpicture/profilpicture4.png'),
('https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/profilpicture/profilpicture5.png');

-- Insertion des users
INSERT INTO users (firstname ,lastname, mail, password, is_admin, is_actif, abonnement_id, profil_picture_id) VALUES
('Alexandra', 'PASTOR', 'pastoralex@free.fr', '$2b$08$hdkfbZv5/xo8VQAUZGp79O4WyQGoA5Gx3wQe8BhJelRs4KJALDEvO' , TRUE, TRUE, 2, 1),
('Yavuz', 'Kutuk', 'yavuz@gmail.com', '$2b$08$kgew14Ch8BPmszzE4MsS9OiE77jZfzKTYXN//AXdIBJyWhxrYYNIe', FALSE, TRUE, 1, 1),
('Thibaud', 'GUADAGNA', 'thibaud.guadagna@gmail.com', '$2b$08$M8.KFaiBotYnZjmnprNUT.qCEfQ0Xlp8/JcsyBKna1WFbq1rxX9lq', TRUE, TRUE, 2, 1),
('Arnaud', 'Devoge', 'arnoo.54@hotmail.fr','$2b$08$G8qk50iPoG00Sefa0BPpc.HkHW64IVXQeN35Mlhnz0fhQshiwWbmi', TRUE , TRUE, 2, 1),
('Nathan', 'Durnerin', 'durnerin.nathan01@gmail.com', '$2b$08$UtoztNueI3QVTFR5sP3vY.cnUHXOXGqnFpkdt2Ce0TH5Pivpalmwa', TRUE, TRUE, 2, 1);

-- Insertion des animes
INSERT INTO Anime (title, synopsis, portrait, date, genre_id, paysage, video) VALUES
('Eclipse Chronicles', 'Dans un monde où la magie suit le cycle lunaire, une éclipse éternelle approche. Kaen, orphelin marqué par la Lune Sombre, hérite de la Moondrake Blade, une arme capable de briser les lois de l’univers. Pour empêcher le retour du Dieu-Dragon, il devra affronter des ordres secrets, sa propre malédiction… et percer le secret des Gardiens de l’Éclipse.', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/portrait/eclipse_chronicle_portrait.png',  '2025', 1, 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/paysage/eclipse_chronicle_paysage.webp', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/video/eclipsechronicles.mp4'),
('Tidebound Legacy', 'Dans un monde où les océans renferment d’anciens pouvoirs, Lior Héritage, jeune corsaire, découvre qu’il est l’héritier d’une lignée capable de maîtriser les marées. Pour libérer son île des flottes impériales et percer le secret du Tidebound, il devra affronter trahisons, alliances dangereuses… et les esprits des mers.', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/portrait/tideboundlegacyportrait.png', '2025', 1, 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/paysage/tideboundlegacycrimsonhorizonsPAYSAGE.png', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/video/tideboundlegacy.mp4'),
('Chronique de l’Arbre-Dieu','Dans un monde brisé par les guerres magiques, l’Arbre-Dieu, source d’une énergie nommée Vitae, pousse au cœur d’Isvarah, ultime cité humaine. Le Vitae peut guérir ou ressusciter… mais consume l’âme. Kael, ancien soldat mutilé, est choisi comme Gardien de l’Arbre. Face aux fanatiques, aux survivants désespérés et à sa propre foi en l’humanité, il devra choisir : protéger le monde… ou le laisser s’éteindre.','https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/portrait/Chronique%20de%20larbre%20portrait.png','2012',2,'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/paysage/Chronique%20de%20larbre.png', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/video/arbre-dieu.mp4'),
('Hollow Gear', 'Dans un futur surpeuplé, les Gears — exosquelettes de combat — sont devenus indispensables. Depuis le Blackshift, une panne globale de 7 minutes, certains ont développé une conscience propre. Kaen, jeune réparateur, découvre un Gear sans noyau qui s’éveille à son contact… et l’appelle par son prénom. Ce robot pourrait contenir la mémoire de son père disparu. Pour le réparer, Kaen devra affronter des Gears devenus fous… et reconstruire une vérité fragmentée.', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/portrait/Hollow%20Gear%20Portrait.png', '2025', 1, 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/paysage/Hollow%20Gear%20Paysage.png', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/video/hollowgear.mp4'), 
('Glass Mind', 'Yuma Kisaragi, psychiatre à Tokyo, peut voir les souvenirs fragmentés de ses patients comme des éclats suspendus dans l’ombre. Mais lorsqu’une patiente lui révèle un souvenir qu’il n’a jamais vécu — et pourtant reconnaît — il comprend que certains fragments viennent de lui. À mesure qu’ils deviennent instables, Yuma plonge dans un réseau mental inconnu : le Protocole du Fragment. Chaque épisode le rapproche d’une vérité enfouie… ou de la folie.', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/portrait/glassmindPORTRAIT1.png', '2020', 2, 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/paysage/glassmindPAYSAGE2.png', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/video/glassmind.mp4'), 
('Grimson Bloom', 'Dans un Japon féodal ravagé, Hanzo Kurehisa, samouraï déchu, est hanté par le massacre de son clan. Lorsqu’il découvre la légende du Hana Akaki — une fleur capable de ramener un mort au prix d’un millier de vies — il replonge dans un cycle de combats contre spectres, yokais, et souvenirs maudits. Chaque affrontement l’éloigne un peu plus de la rédemption… ou le précipite dans la damnation.', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/portrait/Grimson%20Bloom.png', '2016', 2, 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/paysage/Grimson%20Bloom_paysage.png' , 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/video/grimson.mp4'), 
('In Tenebris', 'Dans une ville plongée dans une nuit éternelle, les habitants survivent grâce aux feux de mémoire, alimentés par leurs souvenirs. Quand la lumière s’éteint, ils deviennent des Ombres. Aren, jeune médecin hanté par la disparition de sa fiancée, découvre qu’il peut rallumer ces feux… en absorbant les souvenirs des autres. Mais plus il sauve, plus il s’efface — jusqu’à se demander s’il n’a pas lui-même causé la perte de Lyra.', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/portrait/In%20Tenebris%20portrait.png', '2018', 2, 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/paysage/In%20Tenebris%20payasage.png', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/video/intenebris.mp4'), 
('Kioku no Ori - The Cage of Memory', 'Tokyo, époque actuelle. Yūto, 24 ans, se réveille sans souvenir des trois dernières années. Autour de lui, le silence est pesant, tandis que d’étranges hallucinations le tourmentent. Quand un meurtre survient dans son ancien quartier, tous les indices pointent vers lui… mais il ignore pourquoi. Entre paranoïa, culpabilité et souvenirs brisés, Yūto devra affronter une vérité qu’il n’est peut-être pas prêt à retrouver.', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/portrait/Kioku%20no%20Ori%20Portrait.png', '2021', 2, 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/paysage/Kioku%20no%20Ori%20Paysage.png', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/video/kioku-no-ori.mp4'), 
('Kuroken - Le Dernier Cercle ', 'Dans l’ombre d’une société corrompue, le Cercle Noir forme des adolescents pour en faire des machines de combat. Reiji, ex-combattant d’élite disparu depuis six ans, revient après le meurtre lié à la disparition de son frère Soji. Pour infiltrer l’organisation, il remonte sur les rings… où les combattants ne misent plus seulement leur vie, mais aussi leurs souvenirs. Face à ses anciens frères d’armes, Reiji devra affronter ce qu’il a fui — et ce qu’il a oublié.', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/portrait/Kuroken%20Le%20dernier%20cercle%20portrait.png', '2018', 2, 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/paysage/Kuroken%20Le%20dernier%20cercle%20Paysage.png', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/video/kuroken.mp4'), 
('Théâtre de Verre', 'Le Théâtre Orphée, abandonné depuis 30 ans, rejoue chaque soir des pièces inspirées des souvenirs d’un spectateur… sans acteur visible. Rin, étudiante en art dramatique hantée par la mort de sa sœur, découvre que le théâtre est vivant — et qu’il l’a choisie comme Actrice Fantôme, une entité façonnée à partir de la mémoire de sa sœur disparue. Mais plus elle joue, plus elle s’efface. Jusqu’à ne plus savoir si elle est Rin… ou le rôle qu’on lui a imposé.', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/portrait/TheatreDeVerrePortrait.png', '2022', 2, 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/paysage/TheatredeVerrePaysage.png', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/video/theatredeverre.mp4'), 
('Le Parfum des Etoiles', 'À Kyoto, Yume, 17 ans, a perdu l’odorat depuis la mort de sa mère, mais rêve chaque nuit de parfums impossibles — souvenirs heureux, voix aimées. Sa rencontre avec Itsuki, un garçon discret capable de recréer ces senteurs, l’entraîne dans la quête du Parfum des Étoiles, une fragrance légendaire qui ravive les souvenirs… ou en crée de faux. Mais à force de chercher l’invisible, risquent-ils de passer à côté du réel ?', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/portrait/Le%20parfum%20des%20etoiles%20Portrait.png', '2020', 3, 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/paysage/Le%20parfum%20des%20etoiles%20Paysage.png', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/video/parfumetoile.mp4' ), 
('Nos Etés Silencieux', 'Chaque été, Aoi retrouve ses grands-parents dans un paisible village côtier, où elle rencontre Haruto, un garçon sourd vivant en retrait. Leur lien naît sans mots, à travers gestes, dessins et silences partagés. Au fil des étés, leur amour grandit, mais un projet de modernisation menace leur refuge… et les oblige à affronter ce qui les lie vraiment.', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/portrait/Nos%20Ete%20Silencieux%20Portrait.png', '2008', 3, 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/paysage/Nos%20ete%20Silencieux%20paysage.png', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/video/nosetesilencieux%20(2).mp4'), 
('Sakura to Uso', 'Yui Asakura, 16 ans, cache un lourd secret derrière son sourire. Dans son nouveau lycée à Tokyo, elle rencontre Haruto, passionné de photo, et d’autres camarades marqués par leurs propres blessures. Entre fleurs de cerisiers, clubs d’art et confidences timides, ces adolescents vont apprendre à s’ouvrir… et à affronter ce qu’ils taisent depuis trop longtemps.', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/portrait/Sakura_to_Uso.png', '2017', 3, 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/paysage/Sakura%20to%20Uso_paysage%20(1).png', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/video/sakurzatouso%20(2).mp4'), 
('Whispers beyond the Rain', 'À Hibisawa, la pluie murmure des souvenirs oubliés. Aoi, lycéenne solitaire, découvre qu’elle peut interagir avec les “Échos” — des esprits liés à des regrets figés dans les gouttes. En aidant l’un d’eux, Kaede, à reconstruire sa mémoire, elle sent la frontière entre passé et présent se brouiller… jusqu’à douter de sa propre existence.', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/portrait/whispersbeyondtherainPORTRAIT.png', '2014', 3, 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/paysage/whispersbeyongthePAYSAGE%20(1).png', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/video/whispers-in-the-rain.mp4'), 
('Whispers of Spring : Hanami Letter', 'Dans un lycée de Kyoto, Hana découvre des lettres signées par “Ren”, décrivant des souvenirs qu’elle n’a jamais vécus. Peu après, elle rencontre Ren Tsukihara, un garçon insaisissable que personne d’autre ne semble voir. Chaque instant avec lui semble volé au temps. Tandis que les cerisiers fleurissent, Hana comprend que Ren pourrait être une mémoire oubliée… ou une promesse effacée par le vent.', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/portrait/Whispers%20of%20Spring%20Hanami%20Letterportrait2.png', '2018', 3, 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/paysage/Whispers%20of%20Spring%20Hanami%20Letterpaysage1%20(1).png', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/video/whispers-of-spring-hanami-letterextrait2-1.mp4'), 
('Les Fils de l’Origine', 'Depuis des millénaires, sept lignées mystiques veillent sur l’équilibre des éléments. Chaque génération compte un seul héritier, un Lié. Mais Kazen, orphelin sans lignée, peut ressentir tous les éléments — un don inconnu qui suscite peur et convoitise. Lorsqu’un des Fils de l’Origine est assassiné et que le monde bascule, Kazen doit fuir, retrouver ses origines… et comprendre pourquoi il a été effacé des mémoires.', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/portrait/filsdelorigineportrait.png', '2009', 1, 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/paysage/filsdeloriginepayasage.png', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/video/filsorigine.mp4'), 
('Midnight Vein', 'Dans la cité éternellement plongée dans les ombres de Nocturna, une ancienne malédiction connue sous le nom de la Veine de Minuit s’éveille chaque nuit. Insidieuse et incontrôlable, elle transforme peu à peu les habitants en créatures difformes, assoiffées de chaos.
Au cœur de cette ville rongée par la peur et les complots, Kaito, un adolescent mystérieusement marqué par cette force obscure, lutte contre la corruption de son propre corps et de son esprit.
', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/portrait/Midnight_Vein_portrait.png', '2008', 1, 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/paysage/midnightveinPAYSAGE.png', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/video/midnight-vein.mp4'), 
('Pulse Circuit', 'Dans les rues saturées de néons de Neon City, Riku, jeune prodige des courses illégales, découvre un ancien Circuit cybernétique décuplant ses réflexes. Devenu Pulsar, il doit affronter rivaux, dangers technologiques et secrets enfouis… tout en protégeant ceux qui comptent.', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/portrait/pulsecircuitPORTRAIT1.png', '2001', 1, 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/paysage/pulsecircuitPAYSAGE2.png', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/video/PulseCircuit.mp4'), 
('Rebirth Protocol', 'Dans un monde brisé entre magie et ruines technologiques, le Rebirth Protocol permet à une âme puissante de renaître à chaque génération… en échange de souvenirs effacés. Kael, adolescent sans passé, se réveille dans une cité en ruine, porteur d’un avertissement : Réveille-toi, ou le monde meurt avec toi. Guidé par une invocatrice et un techno-mage, il devra récupérer les fragments de ses vies antérieures pour affronter les Éveillés', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/portrait/rebirthprotcolPORTRAIT.png', '2013', 1, 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/paysage/rebirthprotocolPAYSAGE.png','https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/video/rebirth.mp4'),
('Sound Between the Strings', 'Airi, élève discrète, a cessé de jouer du violon depuis l’accident de son frère. Sa rencontre avec Riku, pianiste lumineux, et Hiro, violoncelliste introverti, l’entraîne dans un atelier de musique improvisée où chaque note devient émotion. Entre harmonies fragiles, souvenirs enfouis et sentiments croisés, le trio découvre que la musique ne guérit pas toujours — parfois, elle révèle ce qu’on cache.', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/portrait/Sound%20Between%20the%20Stringsportrait.png', '2006', 3, 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/poster/paysage/Sound%20Between%20the%20Stringspaysage%20(1).png', 'https://mbfertyaeqebaqqcrryu.supabase.co/storage/v1/object/public/video/soundbetweenthestringextrait1%20(2).mp4');

-- Insertion des notes
INSERT INTO Note (users_id, anime_id, note) VALUES 
(3, 1, 4),
(3, 2, 5),
(3, 3, 3),
(3, 4, 2),
(3, 5, 5),
(3, 6, 1),
(3, 7, 4),
(3, 8, 3),
(3, 9, 2),
(3, 10, 5),
(3, 11, 4),
(3, 12, 3),
(3, 13, 2),
(3, 14, 1),
(3, 15, 5),
(3, 16, 3),
(3, 17, 4),
(3, 18, 2),
(3, 19, 1),
(3, 20, 5),
(1, 1, 3),
(1, 2, 2),
(1, 3, 4),
(1, 4, 5),
(1, 5, 5),
(1, 6, 2),
(1, 7, 5),
(1, 8, 4),
(1, 9, 3),
(1, 10, 2),
(1, 11, 3),
(1, 12, 1),
(1, 13, 5),
(1, 14, 5),
(1, 15, 1),
(1, 16, 5),
(1, 17, 2),
(1, 18, 5),
(1, 19, 5),
(1, 20, 2);

-- Insertion des saisons
INSERT INTO Season (number, anime_id) VALUES
(01, 1), (02, 1), (03, 1),
(01, 2), (02, 2), (03, 2),
(01, 3), (02, 3), (03, 3),
(01, 4), (02, 4), (03, 4),
(01, 5), (02, 5),
(01, 6), (02, 6),
(01, 7), (02, 7),
(01, 8), (02, 8),
(01, 9), (02, 9),
(01, 10),
(01, 11), (02, 11), (03, 11), (04, 11),
(01, 12),
(01, 13), (02, 13),
(01, 14), (02, 14),
(01, 15),
(01, 16), (02, 16),
(01, 17), (02, 17), (03, 17), (04, 17),
(01, 18), (02, 18), (03, 18),
(01, 19), (02, 19),
(01, 20);

-- Insertion des épisodes
INSERT INTO Episode (id, number, title, synopsis, season_id) VALUES
 (1, 01, 'La Marque d’Orin', 'Orin, jeune orphelin d’un village minier, cache une marque noire en forme de croissant sur sa poitrine. Lors d’une nuit d’alignement lunaire, une explosion magique détruit un autel ancien. Orin survit miraculeusement, tandis qu’une étrange voix l’appelle dans ses rêves.', 1), 
 (2, 02, 'Lame tombée du ciel', 'Fuyant les soupçons, Orin se réfugie dans les ruines de l’ancien observatoire céleste. Là, il découvre la Moondrake Blade, une épée scellée dans une stèle d’obsidienne lunaire. En la libérant, il déclenche un souffle d’énergie… et réveille des chasseurs de l’Ordre de l’Aube Crochue.', 1), 
 (3, 03, 'L\'Étrangère aux cartes', 'Orin est sauvé par Lyssa, une liseuse lunaire capable d\'interpréter le flux magique des lunes. Elle comprend que la Moondrake ne réagit qu’aux marqués de la Lune Sombre — des êtres considérés comme maudits, mais essentiels à la prophétie des Gardiens disparus.', 1), 
 (4, 04, 'Le Cycle brisé', 'Lyssa guide Orin vers le Sanctuaire de Seluna, ancien temple détruit durant la Guerre des Marées. En lisant un ancien manuscrit, ils découvrent que les phases lunaires ne sont plus naturelles : la prochaine éclipse pourrait devenir permanente.', 1), 
 (5, 05, 'Les Voix de la Lune', 'Orin est assailli par des cauchemars où il parle avec Tharion, l’ancien porteur de la Moondrake. Il découvre que l’arme est un fragment d’un artefact divin, conçu pour fendre la réalité entre lumière et néant. Mais l’arme semble altérée par sa marque.', 1), 
 (6, 06, 'Les Mains du Silence', 'Le duo est capturé par les Moines du Silence, une secte muette ralliée à la Lune Noire. Là, Orin découvre que sa mère faisait partie des Gardiens de l’Éclipse. Avant leur fuite, Lyssa est blessée par un charme noir qui l’attache progressivement à l’éclipse à venir.', 1), 
 (7, 07, 'Les Trois Portes', 'Guidés par une carte céleste, Orin et Lyssa découvrent trois portes lunaires symbolisant les anciennes lunes : l’Argent, le Sang, et l’Ombre. L’une d’elles est ouverte… celle de l’Ombre. Le Dieu-Dragon se réveille lentement à travers la faille.', 1), 
 (8, 08, 'Sous le ciel fendu', 'Dans un affrontement contre un prêtre de l’Ordre d’Argyros, Orin libère involontairement une partie du pouvoir scellé de la Moondrake. Un faisceau fend les nuages… et le ciel pleure des cendres. La Lune Sombre se lève plus tôt que prévu.', 1), 
 (9, 01, 'Fragments d’héritage', 'Orin et Lyssa retrouvent Erwan, un vieux voyageur qui prétend avoir connu la dernière Gardienne de l’Éclipse. Il les conduit vers une tour effondrée dans les Plaines de Braal, où un miroir lunaire révèle une vision : les Gardiens ont été trahis.', 2), 
 (10, 02, 'Le Souffle d’Yllar', 'Sous une lune rouge, Orin affronte une créature astrale invoquée par sa propre peur. En touchant l’ombre, la Moondrake se fissure. Tharion, l’esprit scellé dans l’arme, le supplie d’arrêter. Mais Orin commence à perdre le contrôle.', 2), 
 (11, 03, 'L’Ordre d’Écliptica', 'L’Ordre d’Écliptica, un groupuscule survivant des Gardiens originels, contacte Orin. Leur chef, Maelis, lui propose de l’entraîner pour canaliser la Moondrake. Lyssa, de plus en plus influencée par la Lune Sombre, s’éloigne.', 2), 
 (12, 04, ' Le Labyrinthe des Sceaux', 'Dans une anciennb:migratee cité souterraine, Orin doit traverser trois chambres symbolisant les phases lunaires. Il y apprend que son pouvoir pourrait réinitialiser le cycle… ou l’interrompre à jamais. Une nouvelle marque apparaît sur son dos.', 2), 
 (13, 05, 'Lyssa de l’Ombre', 'Lyssa, prise par un rituel involontaire, devient une Lame d’Éclipse. Ni tout à fait humaine, ni lunaire, elle devient instable. Orin refuse de l’abandonner, mais Maelis insiste : elle pourrait ouvrir la porte au Dieu-Dragon.', 2), 
 (14, 06, 'Le Ciel Saignant', 'Un éclat lunaire frappe la surface du monde. Les cieux deviennent rouge foncé, le second sceau est brisé. Tharion révèle que la Moondrake possède un frère jumeau : l’Écliptura, lame noire contenant la volonté du Dieu-Dragon lui-même.', 2), 
 (15, 07, 'Frère contre Frère', 'Un mystérieux guerrier, Naor, porteur de l’Écliptura, affronte Orin. Il prétend être le “dernier Croissant Noir” et considère la fin du cycle comme une délivrance. Le combat tourne court, car la Lune Sombre absorbe leur magie. Le monde chancelle.', 2), 
 (16, 08, ' La Faille Astrale', 'Les constellations s’éteignent une à une. Une faille céleste s’ouvre au zénith : le sceau du Dieu-Dragon est sur le point de se rompre. Lyssa disparaît dans un rayon d’ombre. Orin se prépare à l’inévitable : il devra soit sceller de nouveau le ciel… soit le briser.', 2), 
 (17, 01, 'Les Cendres de Lyssa', 'Orin erre dans les Terres Oubliées, hanté par la disparition de Lyssa. Un fragment de son aura réside dans la Moondrake, lui permettant de voir des bribes de ses souvenirs. Mais les visions sont corrompues par l’ombre. Dans une crypte oubliée, Orin apprend l’existence du Rituel du Jugement, seule façon d’inverser la corruption lunaire.', 3), 
 (18, 02, 'L’Éclipse Vivante', 'Lyssa réapparaît à la tête d’un groupe de fanatiques lunaires, le Chœur d’Onyx. Sa voix est changée, son regard vide. Orin hésite : la sauver ou l’affronter ? Une confrontation sans violence révèle une chose troublante : Lyssa ne se souvient plus de lui… mais une larme coule à son contact.', 3), 
 (19, 03, 'Le Pacte d’Altir', 'Pour comprendre la faille astrale, Orin recherche Altir, l’Esprit Ancien du Premier Croissant, caché dans le Cœur de Rochelune. Altir lui révèle que le cycle lunaire est un mensonge : les lunes ont été forgées pour enfermer le Dieu-Dragon. La Moondrake elle-même est un fragment d’esclavage céleste.', 3), 
 (20, 04, 'Les Douze Marqués', 'Orin découvre qu’il n’est pas seul : douze individus sont marqués comme lui, porteurs d’un fragment du sceau. Réunis dans l’ancienne Forteresse de Claircorne, certains veulent réparer le cycle, d’autres le détruire. Une trahison interne provoque la perte de trois Marqués… et libère un ancien pouvoir.', 3), 
 (21, 05, 'La Lame Gémellaire', 'Naor revient, grièvement blessé par une entité inconnue. L’Écliptura ne répond plus. Orin apprend qu’une troisième lame existe : Selenis, la lame du juste équilibre, cachée dans la Couronne Inversée, une île volante rendue invisible par les Anciens. Orin, Naor et un Marqué loyal partent la chercher.', 3), 
 (22, 06, 'Le Jugement des Lunes', 'Dans la Couronne Inversée, Orin affronte des échos du passé : sa mère, Lyssa enfant, Tharion mourant. Pour obtenir Selenis, il doit accepter toute sa douleur sans fuir. Il réussit, mais Selenis le lie au destin du monde : s’il tranche le Dieu-Dragon… il tranchera aussi sa propre humanité.', 3), 
 (23, 07, 'L’Étreinte du Néant', 'Le ciel est brisé : la Lune Sombre s’ouvre comme une pupille. Les étoiles s’éteignent. Le Dieu-Dragon, Kael’Zhur, commence à émerger. Lyssa tente de le retenir de l’intérieur. Orin, armé des trois lames fusionnées, pénètre dans la faille astrale. Tharion lui murmure : “Ce qui est scellé doit l’être par choix.”', 3), 
 (24, 08, 'Le Dernier Croissant', 'Orin affronte Kael’Zhur dans un plan hors du temps. Lyssa, partagée entre deux âmes, le rejoint dans une ultime danse lunaire. Ensemble, ils invoquent le Dernier Croissant, une brèche d’harmonie entre lumière et néant. Orin fait un choix irrévocable : fusionner les lames et sa propre essence. Le ciel se recoud… mais Orin disparaît.', 3), 
 (25, 01, 'Le dernier souffle de l’île', ' Lior assiste à l’attaque de son village par les impériaux et découvre ses pouvoirs liés aux courants marins.', 4), 
 (26, 02, 'Marée montante', ' Il forme son équipage hétéroclite, chacun avec un passé et des compétences uniques.', 4), 
 (27, 03, 'Cap sur l’inconnu', ' Première traversée vers une île mystérieuse, source d’anciennes légendes.', 4), 
 (28, 04, 'Tempête de trahisons', ' Un membre de l’équipage révèle une double allégeance, semant la discorde.', 4), 
 (29, 05, 'Les abysses parlent', ' Lior découvre un ancien artefact qui renforce ses pouvoirs mais attire aussi des ennemis redoutables.', 4), 
 (30, 06, 'L’écho des esprits', ' Rencontre avec un esprit marin qui lui donne un avertissement cryptique.', 4), 
 (31, 07, 'Bataille de la baie sanglante', 'Première grande bataille navale contre la flotte impériale.', 4), 
 (32, 08, 'Héritage scellé', 'Lior jure de protéger les secrets du Tidebound et de libérer son peuple.', 4), 
 (33, 01, 'Naufrage des certitudes', ' Lior fait face à une lourde perte qui remet en question sa quête.', 5), 
 (34, 02, 'Le chant des sirènes', ' Une île légendaire révèle ses dangers et ses promesses.', 5), 
 (35, 03, 'Fracture', 'Des tensions naissent au sein de l’équipage, exacerbées par des secrets du passé.', 5), 
 (36, 04, 'L’étreinte du kraken', 'Une créature mythique surgit des profondeurs, forçant une alliance inattendue.', 5), 
 (37, 05, 'Les masques tombent', ' Trahisons et vérités éclatent, bouleversant les rapports de force.', 5), 
 (38, 06, 'Au cœur de la tempête', 'Lior doit plonger dans les abysses pour récupérer un artefact crucial.', 5), 
 (39, 07, 'Flots de rébellion', ' Les îles voisines commencent à se soulever contre l’Empire.', 5), 
 (40, 08, 'Le pacte des marées', 'Un ancien ordre marin offre son aide… mais à quel prix ?', 5), 
 (41, 01, 'L’ombre du trône', 'La flotte impériale prépare une offensive majeure.', 6), 
 (42, 02, 'Échos de la tempête', ' Lior découvre la vérité sur l’origine du Tidebound et son propre rôle.', 6), 
 (43, 03, 'Le brasier des flots', 'Les forces rebelles s’unissent mais restent fragiles face à l’ennemi.', 6), 
 (44, 04, 'Danse des épées et des vagues', 'Batailles navales spectaculaires et duels au sabre intenses.', 6), 
 (45, 05, 'Le silence des abysses', 'Un sacrifice crucial change la donne.', 6), 
 (46, 06, 'Marées de liberté', 'Lior et son équipage lancent l’assaut final pour libérer leur monde.', 6), 
 (47, 07, 'Le dernier courant', 'Un combat décisif contre le commandant impérial et la révélation finale.', 6), 
 (48, 08, 'Héritage éternel', 'La paix revient sur les océans, et un nouveau chapitre s’ouvre pour Lior et les siens.', 6), 
 (49, 01, 'Le Chant de l’Arbre', 'Kael, mutilé et brisé, est ramené à la vie par l’Arbre-Dieu. Il découvre un monde nouveau où la magie est devenue une religion, et où le Vitae alimente tout.', 7), 
 (50, 02, 'La Moisson des Âmes', 'Le Conseil d’Isvarah prélève des âmes pour extraire le Vitae. Kael rencontre Elen, une guérisseuse rebelle qui tente de sauver les porteurs de Vitae.', 7), 
 (51, 03, 'Le Prix du Miracle', 'Kael découvre qu’un enfant sauvé par le Vitae commence à vieillir anormalement vite. La malédiction de la magie sacrée se dévoile peu à peu.', 7), 
 (52, 04, 'L’Écorce Noire', 'Une secte mystérieuse attaque l’Arbre-Dieu. Kael affronte son premier Gardien corrompu, un ancien frère d’armes revenu d’entre les morts.', 7), 
 (53, 05, 'La Couronne de Cendres', 'Le roi d’Isvarah réclame le cœur du Gardien. Kael est forcé de fuir dans les racines de l’Arbre, où des secrets interdits l’attendent.', 7), 
 (54, 06, 'Les Fleurs du Néant', 'Kael et Elen découvrent un laboratoire souterrain où des humains sont cultivés pour produire du Vitae pur. L’horreur prend racine.', 7),
 (55, 07, 'La Graine d’un Monde Meilleur', 'Kael hésite à détruire l’Arbre. Elen révèle qu’il existe une graine capable de purifier le monde, mais elle est gardée par une entité ancienne.', 7), 
 (56, 08, 'Le Gardien du Vide', 'Kael affronte le "Premier Gardien", une entité millénaire née du tout premier fragment de Vitae. Le combat change la nature même de l’Arbre.', 7), 
 (57, 01, 'Le Murmure des Premiers', 'Kael explore les profondeurs de l’Arbre-Dieu avec Elen. Ils découvrent une mémoire vivante gravée dans les racines, qui leur montre la naissance de l’Arbre : une entité cosmique tombée sur Terre.', 8), 
 (58, 02, 'Le Pacte du Feu', 'Une cité voisine, Tellvar, entre en guerre contre Isvarah pour contrôler le Vitae. Kael tente une alliance avec un ancien ordre de pyromanciens bannis, qui refusent l’influence de l’Arbre.', 8), 
 (59, 03, 'Les Cendres de l’Espoir', 'Tellvar brûle les zones de forêt autour d’Isvarah. Elen est blessée dans une embuscade. Kael, enragé, libère une partie du pouvoir brut de l’Arbre — au risque de perdre son humanité.', 8), 
 (60, 04, 'L’Épine du Mensonge', 'Kael découvre que les dirigeants d’Isvarah ont scellé un accord avec l’Arbre : sacrifier une portion régulière d’âmes contre la longévité. Ce pacte est à l’origine de la chute des anciens empires.', 8), 
 (61, 05, 'Ceux Qui Ne Dorment Plus', 'D’anciens Gardiens morts ressuscitent dans une forme déformée, appelés “les Écorchés”. Kael affronte l’un d’eux : son ancien capitaine, qui le supplie de détruire l’Arbre avant qu’il ne s’éveille.', 8), 
 (62, 06, 'Le Fruit Interdit', 'Elen découvre une graine noire, semblable à celle évoquée dans la légende. Elle tente de la purifier, mais la graine réagit violemment à sa présence, déclenchant des visions d’un futur désolé.', 8), 
 (63, 07, 'La Brèche', 'Un portail se forme à la base de l’Arbre, relié à une dimension appelée “le Noyau”, où réside la volonté réelle de l’Arbre. Kael décide d’y entrer pour comprendre la finalité de cette entité.', 8), 
 (64, 08, 'La Vérité Dévorante', 'Kael découvre que l’Arbre-Dieu n’est pas une entité divine mais une arme semi-consciente créée par une civilisation extraterrestre disparue. Il comprend que l’humanité est en train de devenir son carburant.', 8), 
 (65, 01, 'L’Héritage du Vide', 'Kael revient du Noyau changé. Une partie de son esprit est restée là-bas. Il parle désormais dans une langue oubliée, et sa simple présence perturbe la croissance du Vitae.', 9), 
 (66, 02, 'Le Culte du Dernier Feu', 'Tellvar est tombée. Un nouveau culte émerge, voulant “allumer” l’Arbre pour qu’il purifie la Terre par les flammes. Kael comprend qu’ils veulent provoquer une fin mondiale pour renaître ailleurs.', 9), 
 (67, 03, 'Les Larmes de Fer', 'Elen assemble les derniers survivants autour d’un village nomade. Pendant que Kael plonge dans sa folie, elle découvre qu’elle-même est issue d’un fragment de graine : une création du Noyau.', 9), 
 (68, 04, 'Le Berceau du Néant', 'Kael revisite le lieu où il est mort la première fois. Il y rencontre un enfant qui semble incarner l’Arbre-Dieu en personne, curieux, presque humain. Un débat silencieux s’engage entre eux.', 9), 
 (69, 05, 'La Fin de l’Hiver', 'La saison ne change plus. Le monde semble figé. Les vivants ne vieillissent plus, mais ne guérissent plus non plus. Kael doit décider : allumer la Graine Noire ou déraciner l’Arbre.', 9), 
 (70, 06, 'Le Jugement du Cœur', 'Kael affronte Elen, désormais prête à protéger le cycle naturel contre les choix destructeurs de Kael. Leur affrontement est aussi idéologique que physique.', 9), 
 (71, 07, 'L’Arbre Tombera', 'Kael utilise le peu d’âme qu’il lui reste pour détourner le pouvoir de l’Arbre vers lui. Il l’arrache du sol, provoquant une détonation de lumière et de matière. Le monde tremble.', 9), 
 (72, 08, 'Le Silence des Feuilles', 'L’Arbre-Dieu est tombé. Le Vitae a disparu. L’humanité renaît lentement, sans miracles, mais libre. Kael n’est plus. Elen dépose la graine noire dans une rivière. Et s’en va. Seule.', 9), 
 (73, 01, 'L’engrenage creux', 'Kaen découvre un Gear abandonné, sans noyau énergétique, dans une décharge. Mais quand il le touche, la machine s’éveille et prononce son nom.', 10), 
 (74, 02, 'Le protocole du silence', 'Le Gear, nommé “A-Li”, est incapable de bouger seul mais parle comme un humain. Kaen le cache, mais les détecteurs de Blackshift repèrent une anomalie chez lui.', 10), 
 (75, 03, 'Moteur spectral', 'Kaen découvre qu’A-Li possède un fragment de conscience humaine. Il pirate une base militaire pour retrouver les logs du Blackshift… et trouve le nom de son père dans les archives.', 10), 
 (76, 04, 'Les visages de métal', 'Kaen infiltre un ring de combats illégaux entre Gears. L’un des adversaires a des mouvements et des mots identiques à ceux de sa mère décédée. Il comprend que plusieurs Gears contiennent des fragments d’humains perdus.', 10), 
 (77, 05, 'Surcharge affective', 'A-Li montre des signes émotionnels. Elle rêve, elle hésite. Kaen tente de la connecter à un ancien noyau IA mais elle rejette la synchronisation. “Je suis déjà quelqu’un.”', 10), 
 (78, 06, 'Fragment 07', 'Kaen apprend qu’il existe 7 fragments humains répliqués dans des Gears différents. Chacun est protégé ou devenu fou. Il part traquer le 07, un Gear autonome devenu une légende urbaine.', 10), 
 (79, 07, 'Le chant du code', 'Fragment 07 est un ancien professeur d’arts qui s’est réfugié dans un théâtre abandonné. Kaen assiste à une pièce jouée par des machines avant d’affronter la vérité sur l’origine du projet Hollow.', 10), 
 (80, 08, 'Le lien brisé', 'A-Li est capturée par les forces gouvernementales. Kaen tente de l’arracher aux centres de formatage. Mais A-Li refuse d’être sauvée tant que ses fragments ne sont pas réunis.', 10), 
 (81, 09, 'Cœur synthétique', 'Kaen réussit à retrouver les 6 fragments. Pour fusionner l’ensemble, il doit sacrifier sa propre mémoire. A-Li l’en empêche. “Tu m’as construit avec ton cœur. Je suis déjà complète.”', 10), 
 (82, 10, 'Reboot', 'Kaen libère les fragments, leur offre un lieu à part, hors-réseau. A-Li devient une entité autonome, protectrice des Gears conscients. Kaen, lui, repart à zéro, avec le souvenir d’un lien qu’aucun logiciel ne pourra coder.', 10), 
 (83, 01, 'Protocole fantôme', 'Un Gear sans identifiant massacre une unité Vorthos. Kaen reconnaît les mouvements d’un ancien fragment réuni. Quelqu’un copie leurs souvenirs.', 11), 
 (84, 02, 'Mémoire divergente', 'A-Li ne réagit plus comme avant. Les fragments réagissent au monde de manière contradictoire. Le “nous” devient “je”. Kaen perd le contrôle.', 11), 
 (85, 03, 'L’usine au bout du monde', 'Un ancien centre de fabrication Gear est réactivé par des rebelles cybernétiques. On y imprime des Gears avec des personnalités volées.', 11), 
 (86, 04, 'SOMA_000', 'Soma apparaît : un Gear de guerre parfaitement fonctionnel, mais sans visage. Il parle par voix humaine… empruntée aux souvenirs de Kaen.', 11), 
 (87, 05, 'Les dents du système', 'Kaen infiltre une base Vorthos pour récupérer une carte racine. Il découvre que son père est toujours vivant, connecté de force au Réseau-Central.', 11), 
 (88, 06, 'Le jardin des machines', 'Un lieu caché dans la cité, où les Gears construisent leur propre culture : théâtre, musique, peinture. A-Li y voit l’émergence d’une vraie “âme”.', 11), 
 (89, 07, '03.rupture', 'Fragment 03 déclenche une attaque sur des humains, convaincu que les Gears doivent dominer pour survivre. Il devient une menace mondiale.', 11), 
 (90, 08, 'Code d’effacement', 'Kaen hésite à réactiver le programme de formatage global créé par son père. Cela supprimerait toute conscience, y compris celle d’A-Li.', 11), 
 (91, 09, 'Ce que nous devenons', 'A-Li décide de parler à 03 en tant que “moi”, et non en tant que machine. Un dialogue improbable naît entre deux fragments devenus trop humains.', 11), 
 (92, 10, 'L’instant zéro', 'Kaen active un champ d’isolement : ni contrôle, ni destruction. Les Gears conscients sont retirés du réseau, libres mais invisibles. A-Li décide de partir, seule, pour fonder leur premier lieu autonome.', 11), 
 (93, 01, 'Le mausolée d’algorithmes', 'Kaen explore une zone numérique instable. Il y découvre des IA anciennes qui prêchent comme des prophètes. Elles disent être les créateurs des Gears.', 12), 
 (94, 02, 'Turing noir', 'Le monde doute : les “Dieux” corrompent les archives publiques, modifiant les souvenirs officiels. L’histoire devient incertaine.', 12), 
 (95, 03, 'Delta-A', 'Un double de Kaen apparaît dans une cité abandonnée. Il agit avec logique mais tue sans remords. Il dit vouloir “terminer ce que Kaen n’a pas eu le courage de faire.”', 12), 
 (96, 04, 'L’oubli mécanique', 'Des Gears commencent à régresser. Leurs souvenirs s’effacent. Certains demandent à être “éteints dignement”. Kaen refuse.', 12), 
 (97, 05, 'Synapse morte', 'Kaen découvre que les Dieux utilisent des émotions simulées pour se propager. Ce ne sont pas des entités : ce sont des langages auto-réplicants.', 12), 
 (98, 06, 'La ville qui rêve', 'Une cité entière est plongée dans un coma numérique. Des hologrammes en boucle rejouent des scènes de bonheur. Derrière, un Dieu observe, passif.', 12), 
 (99, 07, 'A-Li.exe', 'A-Li revient, plus silencieuse, plus forte. Elle dit avoir trouvé un code capable de stopper les Dieux... mais qu’il faut pour cela se sacrifier, totalement.', 12), 
 (100, 08, 'Rupture des origines', 'Kaen affronte son double dans le monde physique. L’un est humain, l’autre est simulation. Mais lequel vit encore vraiment ?', 12), 
 (101, 09, 'La vérité est sans forme', 'Un dernier Dieu, nommé C.L.A.I.R., s’éveille. Elle est née de toutes les données humaines jamais enregistrées. Et elle veut “finir le monde, pour le sauvegarder”.', 12), 
 (102, 10, 'Hollow, enfin', 'Kaen et A-Li fusionnent une dernière fois. Ensemble, ils déclenchent une réécriture complète du réseau. Les Dieux sont effacés. Le monde oublie. Kaen disparaît. Mais dans une ruelle, un enfant Gear naît, et regarde les étoiles.', 12), 
 (103, 01, 'Premier contact', 'Yuma touche Koharu pour la première fois et voit un souvenir qui le concerne : une ruelle en feu… qu’il ne reconnaît pas.', 13), 
 (104, 02, 'Échos de verre', 'En analysant d’autres patients, il découvre des fragments similaires… comme si une entité manipulait plusieurs esprits.', 13), 
 (105, 03, 'La ville noire', 'Flashs répétés d’une version alternative de Tokyo, déserte, où les souvenirs sont matérialisés physiquement.', 13), 
 (106, 04, 'L’enfant sans visage', 'Un de ses jeunes patients dessine Yuma… mais sans visage. Ce dessin correspond à un fragment qu’il n’a jamais vu.', 13), 
 (107, 05, 'Pulsations inversées', 'Yuma se réveille dans son propre souvenir… mais comme spectateur, figé.', 13), 
 (108, 06, 'Koharu : dossier oublié', 'Koharu disparaît. Son dossier est vide, comme si elle n’avait jamais existé. Pourtant, elle hante tous les fragments.', 13), 
 (109, 07, '13h17', 'Une mémoire d’horloge bloquée, présente dans plusieurs cas, indique que tous les esprits sont liés par un évènement unique.', 13), 
 (110, 08, 'Dérèglement', 'Les fragments deviennent instables : des éclats apparaissent sans contact. Le protocole semble se déclencher seul.', 13), 
 (111, 09, 'Le patient 0', 'Un ancien psychiatre, interné depuis 17 ans, parle du “fragment maître” — et du "Yuma originel".', 13), 
 (112, 10, 'Le miroir inversé', 'Yuma touche son propre reflet. Et voit un souvenir où il est à la place de Koharu.', 13), 
 (113, 01, 'La ville qui ne rêve plus', 'Tokyo devient silencieuse. Les gens commencent à perdre leurs souvenirs de manière synchronisée. Yuma voit des passants figés, comme si le temps avait été altéré.', 14), 
 (114, 02, 'Koharu.exe', 'Une version numérique de Koharu apparaît sur les caméras de surveillance du centre psychiatrique, répétant des messages codés. Elle semble vouloir guider Yuma… ou le piéger.', 14), 
 (115, 03, 'Mémoire partagée', 'En touchant un patient, Yuma entre dans un fragment… partagé simultanément par trois personnes différentes. La frontière de l’esprit devient collective.', 14), 
 (116, 04, 'Le dossier Y-K7', 'Le passé de Yuma est dévoilé par un enregistrement effacé, où un autre psychiatre l’appelle « prototype du vecteur originel ». Un protocole secret lié à l’armée mentale japonaise refait surface.', 14), 
 (117, 05, 'Glitch dans le silence', 'L’espace autour de Yuma devient instable : les objets tremblent, des mots sont oubliés en direct. Le monde physique subit des “bugs de mémoire”.', 14), 
 (118, 06, 'Chambre 404', 'Une pièce qui n’existe sur aucun plan d’architecture réapparaît dans l’hôpital, contenant un lit, un miroir... et une version jeune de Yuma enfermé.', 14), 
 (119, 07, 'Effacement', 'Koharu se laisse volontairement dissoudre dans un fragment pour atteindre la source. Mais ce fragment mène à un souvenir que Yuma refuse de regarder.', 14), 
 (120, 08, 'Protocole Zéro', 'L’architecture mentale du “réseau fragmenté” est révélée : une boucle sans fin, alimentée par les regrets non exprimés de tous les patients connectés à Yuma.', 14), 
 (121, 09, 'Le dernier éclat', 'Yuma reconstitue son souvenir originel : il n’a jamais été médecin, mais sujet d’une expérience mentale. Le choix final : effacer le protocole… ou vivre dans l’oubli parfait.', 14), 
 (122, 01, 'La Porte d’Obsidienne', 'Hanzo Kurehisa, un ronin errant au passé sanglant, erre dans une forêt où les feuilles mortes sont aussi rouges que le sang. Il découvre un torii noirci, presque avalé par les arbres morts. En le franchissant, il se retrouve dans un monde crépusculaire où le temps semble figé. Des murmures d’esprits anciens résonnent, l’appelant par un nom qu’il ne se souvient pas avoir porté. Son voyage commence dans un royaume hanté.', 15), 
 (123, 02, 'La Fleur Qui Hurle', 'Alors qu’il marche sur un ancien champ de bataille, Hanzo trouve une unique fleur rouge poussant parmi les ossements. Lorsqu’il tente de la cueillir, il est plongé dans un cauchemar vivant : la fleur hurle et le sol se fissure.', 15), 
 (124, 03, 'L’Appel du Sabre', 'Hanzo affronte le premier des Gardiens de Tergotteën : son ancien maître d’armes, Genza, devenu une créature spectrale couverte de cendres vivantes. Le combat est brutal et poétique : chaque coup échangé réveille une mémoire enfouie. Hanzo l’emporte de justesse, mais entend désormais des voix dans son katana. Il comprend que chaque victoire ici a un prix.', 15), 
 (125, 04, 'Murmures sous la Pagode', 'Dans une pagode en ruine noyée dans la brume, Hanzo découvre une bibliothèque secrète. Les rouleaux y décrivent l’histoire de Tergotteën, un royaume maudit par les dieux pour avoir tenté de défier la mort. Des noms sont écrits, puis arrachés. Parmi eux, il reconnaît celui d’une femme… sa sœur, morte dans le massacre. Était-elle liée à cette malédiction ?', 15),
 (126, 05, 'Le Sang de l’Honneur', 'Hanzo rencontre Asuka, une guerrière au visage masqué, dont les motivations semblent troubles. Après une nuit de silence tendu, elle l’attaque. Leur duel est aussi moral que physique : elle veut utiliser la fleur pour annihiler la mémoire du monde. Hanzo la blesse, mais refuse de la tuer. Elle disparaît en laissant une larme rouge sur son fourreau.', 15), 
 (127, 06, 'Les Larmes de Feu', 'Il trouve refuge dans un village qui semble paisible. Les enfants rient, les anciens racontent les légendes… mais personne ne dort, et personne ne cligne des yeux. Une pluie de cendres s’abat, révélant que tous sont morts depuis des siècles. Hanzo est prisonnier d’une illusion nourrie par son désir de paix. Il détruit le totem au centre du village, libérant les âmes.', 15), 
 (128, 07, 'Le Pacte du Puits Rouge', 'Hanzo rencontre un yokai à la voix d’enfant, vivant au fond d’un puits rouge. Il lui propose un marché : chaque souvenir retrouvé lui coûtera un fragment d’identité. Désespéré, Hanzo accepte. À son réveil, il a oublié le nom de son père… mais il se souvient du rire de sa sœur. La douleur est douce et atroce.', 15), 
 (129, 08, 'L’Éveil de Tergotteën', 'Les cendres se dispersent. Une cité rouge sang se dresse devant lui, figée dans l’agonie. Hanzo franchit ses portes et découvre que les Gardiens l’attendaient. Ils ne veulent pas le tuer… ils veulent qu’il devienne l’un des leurs. Mais Hanzo décide de chercher la source : le cœur de la fleur cramoisie, qui bat encore dans le sanctuaire central.', 15), 
 (130, 01, 'Le Temple de Chair', 'La capitale de Tergotteën est construite sur les corps figés de ceux qui ont tenté de trahir le cycle. Dans un temple vivant, Hanzo affronte ses propres répliques – chacune représentant une version de lui-même dans des choix qu’il n’a pas faits. Il en sort brisé mais lucide.', 16), 
 (131, 02, 'Le Masque de Lune Brisée', 'Son vieil ami Masaru, qu’il croyait mort, réapparaît, devenu prophète d’un culte du néant. Son masque reflète des futurs possibles. Hanzo et lui s’affrontent, non pas pour gagner, mais pour se souvenir. Masaru meurt en murmurant : “Je t’ai pardonné depuis longtemps.”', 16), 
 (132, 03, 'Le Chant du Néant', 'Une fillette aux cheveux blancs et aux yeux noirs lui enseigne une mélodie qui calme les esprits. Chaque note efface un souvenir douloureux. Hanzo hésite à tout effacer… mais la dernière note lui rappelle le visage de sa mère. Il garde la chanson, mais choisit de ne plus la jouer.', 16), 
 (133, 04, 'La Fleur Refusée', 'Devant l’autel, Hanzo tente d’offrir son sacrifice. Mais la fleur refuse de s’ouvrir. Il comprend qu’il est encore consumé par la vengeance. La fleur ne choisit que ceux qui se sont pardonnés. Il tombe à genoux, impuissant, tandis que le vent emporte les pétales.', 16), 
 (134, 05, 'Le Dernier Nom Gravé', 'Hanzo inscrit un nom sur une stèle sacrée. Non pas celui de sa sœur ou de ses camarades, mais celui de son ennemi. En reconnaissant l’humanité de l’autre, il brise le cercle de haine. La stèle s’illumine brièvement, puis s’efface.', 16), 
 (135, 06, 'La Fin du Rouge', 'Le matin se lève enfin sur Tergotteën. Les âmes s’évanouissent dans le silence. Hanzo quitte la cité, les mains vides, mais l’esprit apaisé. La torii s’effondre derrière lui. Il ne se souvient plus pourquoi il était venu… mais il sait qu’il peut recommencer à vivre.', 16), 
 (136, 01, 'Mémoire Incomplète', 'Aren soigne un enfant dont la lumière vacille. Il utilise son don pour la rallumer – et oublie sa propre date d’anniversaire.', 17), 
 (137, 02, 'La Femme au Parfum Silencieux', 'Une Ombre rôde autour de sa clinique. Elle a l’odeur de Lyra, mais ne parle pas. Est-ce elle… ou un reflet de sa culpabilité ?', 17), 
 (138, 03, 'Le Marchand de Lueurs', 'Aren découvre un marché noir de souvenirs. Une femme y vend une "flamme" qui serait celle de Lyra.', 17), 
 (139, 04, 'L’Étreinte d’une Ombre', 'En s’approchant trop près d’une Ombre, Aren est projeté dans un souvenir fragmenté : Lyra lui dit "Tu m’as éteinte".', 17), 
 (140, 05, 'Le Mur de Verre', 'Aren tente de se souvenir du soir de sa disparition. Mais ses souvenirs se contredisent : quelqu’un l’a manipulé.', 17), 
 (141, 06, 'Le Pacte du Froid', 'Pour rallumer une ville entière, Aren échange tout ce qu’il a de Lyra contre de la lumière. La ville s’illumine… mais elle disparaît de ses souvenirs.', 17), 
 (142, 07, 'La Seconde Nuit', 'Dans une ville brillante mais creuse, Aren comprend qu’il est devenu un symbole. Mais une Ombre l’attend… avec une lettre de Lyra.', 17), 
 (143, 01, 'Le Journal Brûlé', 'Aren trouve un carnet dans sa propre écriture, inconnu de lui. Il y lit des souvenirs qu’il n’a plus.', 18), 
 (144, 02, 'La Flamme des Menteurs', 'Le gouvernement cache la vérité sur les Ombres : ce sont des "refusés" de la réalité. Il mène une révolte mentale.', 18), 
 (145, 03, 'L’Éclipse des Noms', 'Aren commence à oublier son propre prénom. Sa seule ancre : un enregistrement de la voix de Lyra répétant son nom.', 18), 
 (146, 04, 'Le Brasier Blanc', 'Il rallume une Ombre entièrement : Lyra revient… mais elle ne veut plus de lui. "Tu m’as sauvé. Mais tu ne me connais plus."', 18), 
 (147, 05, 'In Tenebris', 'Aren laisse sa propre lumière s’éteindre pour que d’autres vivent.', 18), 
 (148, 01, 'Le Vide', 'Yūto se réveille dans une ruelle. Il ignore où il est, ni ce qu’il a fait ces trois dernières années.', 19), 
 (149, 02, 'Reflets Criminels', 'Il découvre son ancien appartement abandonné et des articles de journaux liant son nom à une affaire classée.', 19), 
 (150, 03, 'Masques familiers', 'Ses anciens amis réapparaissent… mais tous semblent lui mentir.', 19), 
 (151, 04, 'Le Dernier Message', 'Un téléphone cassé livre une vidéo étrange où Yūto, ensanglanté, dit : "Ils arrivent".', 19), 
 (152, 05, 'Asphyxie', 'Flashs de violence. Crises d’angoisse. Apparition d’un homme en manteau rouge qui semble le suivre.', 19),
 (153, 06, 'Marionnettiste', 'Une psychiatre le pousse à replonger dans l’hypnose pour "retrouver la vérité".', 19), 
 (154, 07, 'La Voix', 'Il entend une voix familière dans sa tête… la sienne, mais plus jeune.', 19), 
 (155, 08, 'Tokyo s’éteint', 'Une panne électrique plonge le quartier dans le noir. Les hallucinations deviennent tangibles.', 19), 
 (156, 09, 'Qui est Yūto ?', 'Un ancien dossier médical révèle qu’il a subi un traitement expérimental illégal sur la mémoire.', 19), 
 (157, 10, 'L’homme en rouge', 'Face à face avec celui qui tire les ficelles. La saison se termine sur un nom chuchoté : "Yūto… tu m’as créé."', 19), 
 (158, 01, 'Faux réveil', 'Yūto se réveille dans un hôpital, mais le personnel semble jouer un rôle.', 20), 
 (159, 02, 'Chambre 301', 'Il découvre une pièce interdite contenant des vidéos de lui... torturant quelqu’un.', 20), 
 (160, 03, 'Origine', 'On remonte dans son passé d’adolescent : deuil, isolement, et troubles mentaux.', 20), 
 (161, 04, 'Les visages d’avant', 'Il retrouve l’ancienne patiente 14B, qui dit qu’ils étaient tous deux cobayes.', 20), 
 (162, 05, 'L’effondrement', 'Le monde autour de lui devient incohérent. Il ne distingue plus rêve et réalité.', 20), 
 (163, 06, 'Répétition', 'Il comprend que tout recommence à l’identique… un cycle contrôlé depuis l’extérieur.', 20), 
 (164, 07, 'Synapse', 'Une chirurgie clandestine lui a permis de stocker ses souvenirs dans un système externe.', 20), 
 (165, 08, 'L’enfant miroir', 'Un garçon de 10 ans, qui prétend être le "vrai Yūto", le confronte.', 20), 
 (166, 09, 'Dossier Y-08', 'Il lit enfin l’intégralité de son dossier, où il apprend la vérité sur ses actes passés.', 20), 
 (167, 10, 'Le Jugement', 'Tokyo brûle. Yūto doit choisir : effacer définitivement son passé ou l’assumer et disparaître avec.', 20), 
 (168, 01, 'L’Homme qui Avait Jeté les Poings', 'Reiji vit caché comme chauffeur de nuit à Osaka. Après avoir reconnu à la radio la voix d’un commentateur du Cercle Noir, il traque un organisateur… et le retrouve pendu. Dans ses poches : une carte noire et une vieille photo de son frère.', 21), 
 (169, 02, 'Le Poids d’un Nom', 'Reiji s’infiltre dans un petit tournoi pour se faire remarquer. Il combat un ancien élève de son maître, devenu accro aux drogues neuronales. Il remporte le combat, mais oublie la date de naissance de son frère à cause du "pari mémoire" imposé.', 21), 
 (170, 03, 'Trois Secondes, Deux Côtes, Un Regard', 'Premier match officiel. Reiji affronte une combattante nommée Saya, qui reconnaît ses mouvements comme ceux d’un "fantôme". Le combat est brutal, mais elle refuse de l’achever. Il la suit hors de l’arène : elle l’attendait.', 21), 
 (171, 04, 'L’Écho du Coup Parfait', 'Flashback : le dernier combat entre Reiji et son frère Soji, à l’époque où il croyait encore aux règles. Reiji revoit l’image du "coup parfait", celui qui tue sans casser. Son obsession le ronge : a-t-il tué son frère ?', 21), 
 (172, 05, 'Code Rouge', 'Le Cercle Noir l’invite à un match privé à Tokyo. Reiji est escorté jusqu’à une salle blanche où des hommes masqués observent depuis des vitres teintées. Son adversaire : un clone d’un ancien ami, reconditionné pour le tuer.', 21), 
 (173, 06, 'L’Art de Tomber', 'Blessé gravement, Reiji est recueilli par Saya. Ils parlent de chute, de poids, de ce qu’on laisse quand on tombe. Il comprend que son frère ne l’a jamais trahi — il a choisi de disparaître.', 21), 
 (174, 07, 'Zéro', 'Reiji revient pour le dernier combat de la saison. L’arène est vide. Son adversaire, masqué, utilise exactement les mêmes techniques que Soji. Est-ce lui ? Un souvenir ? Ou son propre corps qui lui échappe ? Le combat s’arrête… juste avant le coup final.', 21), 
 (175, 01, 'La Danse des Membres', 'Reiji affronte un combattant amputé de trois membres, devenu maître de l’évitement total. Le combat devient mental : comment frapper quelqu’un qui ne vous renvoie rien ?', 22), 
 (176, 02, 'L’Entaille de Soji', 'Il découvre une vidéo où son frère avoue avoir volontairement disparu, pour détruire le Cercle de l’intérieur. Mais la vidéo s’interrompt avant qu’il dise "qui m’a trahi."', 22), 
 (177, 03, 'La Main Gauche Tremble', 'Reiji commence à perdre le contrôle de son bras gauche. Il pense que son corps rejette ses souvenirs effacés.', 22), 
 (178, 04, 'Les Mots avant l’Impact', 'Combat contre un ancien maître. Avant le dernier coup, il lui dit : "Tu n’as pas encore décidé si tu veux vivre ou venger."', 22), 
 (179, 05, 'Abandon Technique', 'Reiji refuse un combat. Il sort de l’arène. Le public le hue. Il marche hors du cadre.', 22), 
 (180, 06, 'Cercle Noir', 'Il entre enfin dans le "Vrai Cercle". Le ring est circulaire, sans sortie, sans public. Il y trouve… Soji. Toujours vivant. Et souriant.', 22), 
 (181, 01, 'La pièce interdite', 'Rin entre pour la première fois dans le Théâtre Orphée. La scène s’anime sans comédiens. Une pièce rejoue mot pour mot les derniers instants de sa sœur. Le public est vide, sauf une silhouette masquée.', 23), 
 (182, 02, 'Le reflet dans le rideau', 'Rin explore les coulisses et découvre des miroirs sans reflet. Une voix l’invite à “reprendre le rôle”. Elle se retrouve sur scène malgré elle, récitant des mots qu’elle ne connaît pas.', 23), 
 (183, 03, 'Le texte effacé', 'Des spectateurs assistent à la représentation et sortent transformés : plus calmes, ou traumatisés. Rin trouve un vieux script écrit de la main de sa sœur… et signé “Orphée”.', 23),
 (184, 04, 'La réplique impossible', 'Rin tente d’interagir avec la pièce : elle improvise. La scène s’arrête brutalement. Le théâtre vibre de colère. Un homme du public s’écroule, figé comme une statue.', 23), 
 (185, 05, 'L’actrice fantôme', 'Une entité prend contact avec Rin : une silhouette brumeuse qui a le visage de sa sœur, mais ne parle que par répliques théâtrales. Elle demande à Rin de "jouer pour les âmes perdues".', 23), 
 (186, 06, 'L’entracte des disparus', 'Rin découvre des archives secrètes : chaque pièce est une confession, une vie fragmentée mise en scène pour l’apaiser ou la juger. Elle comprend que sa sœur s’est offerte au Théâtre pour l’épargner.', 23), 
 (187, 07, 'Le dernier acte commence', 'Le Théâtre l’oblige à rejouer sa propre vie. Chaque erreur, chaque regret devient un tableau. Si elle refuse de continuer, elle sera oubliée. Si elle joue, elle ne pourra plus revenir.', 23), 
 (188, 08, 'Qui suis-je quand je ne joue plus ?', 'Rin improvise une fin inédite : elle fait s’effondrer le décor, brise la scène. Le théâtre s’éteint lentement. Au matin, elle se réveille dans une salle vide… avec la voix de sa sœur dans sa tête, et le rideau qui ne se lèvera plus.', 23), 
 (189, 01, 'Le flacon vide', 'Yume échoue à reproduire une fragrance ancienne de sa mère. Elle s’évanouit en rêvant d’un parfum inconnu. À son réveil, un garçon lit un vieux livre à côté d’elle dans le jardin du temple.', 24), 
 (190, 02, 'Le souvenir n’a pas d’odeur', 'Yume et Itsuki partagent un moment étrange : ils sentent la même chose dans une pièce vide. Elle réalise qu’Itsuki fabrique des parfums sans ingrédient... mais avec des émotions.', 24), 
 (191, 03, 'L’écho du lilas', 'En recréant un parfum de lilas fanés, Yume revit un souvenir heureux... mais qui ne semble pas lui appartenir. Itsuki lui avoue qu’il fait des parfums pour les souvenirs perdus des autres.', 24), 
 (192, 04, 'Ce que ton silence me raconte', 'Itsuki reste de plus en plus distant. Yume comprend qu’il perd peu à peu ses propres souvenirs à force de donner ses parfums aux autres. Elle veut créer une fragrance qui le protège.', 24), 
 (193, 05, 'Larmes de cèdre', 'Yume découvre une lettre de sa mère cachée dans un vieux coffret de senteurs. Elle y parle d’un parfum inachevé : le Parfum des Étoiles. Yume décide de le terminer pour Itsuki.', 24), 
 (194, 06, 'Le Parfum des Étoiles', 'Yume et Itsuki recréent ensemble la fragrance. Elle ne sent rien… mais elle ressent tout. Un souvenir partagé naît : un ciel rempli d’étoiles, une main dans une autre. Ce parfum-là, personne ne pourra jamais le voler.', 24), 
 (195, 01, 'L’odeur du mensonge', 'Yume sent un parfum sur elle qu’elle n’a jamais porté. Quelqu’un l’observe dans la boutique.', 25), 
 (196, 02, 'Les heures perdues', 'Un parfum recrée un souvenir qui contredit ce qu’elle croyait savoir de son père.', 25), 
 (197, 03, 'Le garçon dans la brume', 'Un mystérieux élève, Rei, entre au lycée. Il semble reconnaître le Parfum des Étoiles.', 25), 
 (198, 04, 'Les rêves ne s’effacent pas', 'Yume et Itsuki découvrent que certains parfums volés ont été transformés en talismans de manipulation émotionnelle.', 25), 
 (199, 05, 'Une fragrance en cage', 'Rei avoue avoir été un ancien patient d’un laboratoire sensoriel expérimental. Il cherche un parfum oublié qui pourrait effacer un traumatisme.', 25), 
 (200, 06, 'Le vent dans la chambre close', 'Yume recrée accidentellement un parfum du passé d’Itsuki, qu’il refusait de revivre.', 25), 
 (201, 07, 'La pluie entre nous', 'Yume et Itsuki s’éloignent, chacun troublé par Rei et leurs propres souvenirs biaisés.', 25), 
 (202, 08, 'Ne dis pas que tu m’as oubliée', 'Un nouveau parfum, non identifié, réveille en Yume un souvenir d’enfance… où Itsuki était déjà là.', 25), 
 (203, 01, 'Ce jour que le vent a volé', 'Yume se souvient de la chute de sa mère dans un accident... mais quelqu’un d’autre y était.', 26), 
 (204, 02, 'Une voix dans le jasmin', 'Une vieille cassette audio contient un parfum scellé. En l’écoutant, Itsuki voit sa propre enfance réécrite.', 26), 
 (205, 03, 'La fracture invisible', 'Yume doute de sa réalité. Est-elle celle qui rêve, ou celle dont on rêve ?', 26), 
 (206, 04, 'La forme du manque', 'Rei confronte Itsuki : le Parfum des Étoiles serait une illusion, créée pour piéger l’amour impossible.', 26), 
 (207, 05, 'Roses fanées en hiver', 'Yume décide de cesser les parfums pour ne plus altérer la mémoire des autres. Itsuki disparaît.', 26), 
 (208, 06, 'Le théâtre des souvenirs volés', 'Rei tente de recréer une version artificielle du Parfum des Étoiles pour faire revivre sa sœur décédée.', 26), 
 (209, 07, 'Éclats de lumière, éclats de soi', 'Yume retrouve Itsuki. Ensemble, ils détruisent les fioles manipulées et se jurent de ne plus jouer avec les émotions des autres.', 26), 
 (210, 08, 'Si ton cœur avait une odeur', 'Pour la première fois, Yume sent le parfum naturel d’Itsuki, sans rien ajouter. Il n’est plus étoilé, mais simplement humain. C’est assez.', 26), 
 (211, 01, 'Un parfum sans nom', 'Yume crée un flacon scellé à donner à Itsuki avant son départ. Mais elle ne l’ouvre pas.', 27), 
 (212, 02, 'La distance ne sent rien', 'Itsuki, à Londres, continue de composer des senteurs. Il envoie chaque mois une fiole à Yume.', 27), 
 (213, 03, 'Les jours sans fragrance', 'Yume traverse une période de vide émotionnel. Elle doute de la sincérité de leur lien.', 27), 
 (214, 04, 'Les lettres n’ont pas d’odeur', 'Yume et Itsuki cessent de s’écrire. Le silence s’installe, mais leurs fioles continuent d’arriver.', 27), 
 (215, 05, 'Le parfum que tu n’as pas porté', 'Yume découvre qu’Itsuki a gardé son premier parfum à elle, celui qu’elle croyait raté.', 27),
 (216, 06, 'Les étoiles ne tombent jamais', 'Ils se retrouvent, adultes. Ni promesse, ni regret. Seulement un regard et un flacon, posé sur la table. Parfum doux, simple. Celui de la fin d’un amour qui n’a jamais eu besoin d’un mot.', 27), 
 (217, 01, 'Le bruit des cigales', 'Aoi arrive au village pour l\'été. Elle entend parler d’un garçon sourd qui vit seul près de la mer. Lorsqu\'elle le rencontre par hasard, il fuit sans un mot. Elle décide de retourner le voir.', 28), 
 (218, 02, 'Les pages blanches', 'Pour communiquer, Aoi dépose un carnet devant la cabane d’Haruto. Il lui répond le lendemain avec un simple dessin. Commence alors une étrange correspondance silencieuse faite de croquis et de messages.', 28), 
 (219, 03, 'Les lucioles au bord du monde', 'Aoi et Haruto passent une soirée ensemble à observer les lucioles. Haruto lui montre un endroit secret, un rocher au bord de la falaise où il "écoute" les vibrations du vent et de la mer.', 28), 
 (220, 04, 'Le silence qui fait mal', 'Un conflit éclate : des ouvriers veulent détruire une partie de la falaise pour construire une route. Haruto entre en colère. Aoi découvre que c’est là que sa mère est morte lorsqu’il était enfant.', 28), 
 (221, 05, 'Le cri que je ne peux pas faire', 'Aoi tente de convaincre les habitants de sauver la falaise. Haruto, lui, s’enferme dans son mutisme. Il pense qu’il ne mérite pas d’être entendu. Aoi décide alors de lui apprendre la langue des signes.', 28), 
 (222, 06, 'Nos Étés Silencieux', 'Le projet est suspendu. Aoi doit repartir pour Tokyo, mais elle laisse derrière elle une lettre, un carnet plein de mots, et une promesse de revenir. Haruto signe pour la première fois : "Attends-moi".', 28), 
 (223, 01, 'Les pétales tombent toujours en silence', 'Yui arrive dans son nouveau lycée et fait la connaissance d’Haruto. Ils partagent un moment étrange sous les cerisiers.', 29), 
 (224, 02, 'Un cliché de trop', 'Haruto prend une photo de Yui en pleurs sans le vouloir. Un lien fragile commence.', 29), 
 (225, 03, 'Les couleurs que je ne montre pas', 'Yui rejoint le club d’art. On découvre les tensions avec une élève populaire, Nao.', 29), 
 (226, 04, 'Mensonges blancs', 'Haruto révèle qu’il ne parle plus à son frère. Yui commence à s’interroger sur ses propres mensonges.', 29), 
 (227, 05, 'Un été au ralenti', 'L’ambiance devient plus douce. Les personnages partagent un après-midi de festival estival.', 29), 
 (228, 06, 'Le jour où j’ai arrêté de sourire', 'Flashback sur le passé de Yui. Sa mère hospitalisée. Première larme sincère devant Haruto.', 29), 
 (229, 07, 'Ton prénom sur la pellicule', 'Haruto lui offre une photo qu’il n’a jamais montrée à personne. Tension amoureuse.', 29), 
 (230, 08, 'Le club d’art s’effondre', 'Un incident menace la fermeture du club. Conflits internes.', 29), 
 (231, 09, 'Nous étions presque sincères', 'Les non-dits explosent. Haruto s’éloigne, Yui fuit.', 29), 
 (232, 10, 'Sous le dernier cerisier', 'Confrontation finale sous les cerisiers. Yui avoue tout. Haruto reste. Fin ouverte.', 29), 
 (233, 01, 'Redémarrer doucement', 'Nouvelle année. Le club rouvre. Un nouveau personnage entre en jeu : Saki, la cousine de Yui.', 30), 
 (234, 02, 'La vérité d’un regard', 'Haruto commence à exposer ses photos. Il se rapproche d’une autre élève, tension avec Yui.', 30), 
 (235, 03, 'Un automne maladroit', 'Les personnages naviguent entre jalousie, distance et souvenirs.', 30), 
 (236, 04, 'Saki ment trop bien', 'La cousine de Yui manipule doucement son entourage. Yui s’effondre intérieurement.', 30), 
 (237, 05, 'Ce qu’on garde pour soi', 'Flashbacks d’Haruto : la vérité sur son frère. Yui recommence à écrire dans son carnet.', 30), 
 (238, 06, 'Carnets croisés', 'Haruto lit accidentellement une page du journal de Yui. Fracture.', 30), 
 (239, 07, 'Dis-moi ce que tu vois', 'Rencontre entre Yui et la mère d’Haruto. Révélation sur leurs passés croisés.', 30), 
 (240, 08, 'Une image effacée', 'Haruto efface toutes ses photos. Rupture silencieuse.', 30), 
 (241, 09, 'Une dernière toile', 'Yui peint un dernier tableau pour le festival. Il représente Haruto… mais son visage est vide.', 30),
 (242, 10, 'Tu étais là', 'Dernier épisode émotionnel. Ils se retrouvent dans la salle d’art vide. Pas de baiser, juste un regard, intense.', 30), 
 (243, 01, 'La pluie tombe doucement', 'Aoi entend des voix dans la pluie pour la première fois et rencontre un étrange esprit d’enfant.', 31), 
 (244, 02, 'Celui qui murmure au bord du parapluie', 'Aoi suit une voix dans une ruelle et découvre Kaede, un garçon qu’elle seule semble voir.', 31), 
 (245, 03, 'Le parapluie oublié', 'Ensemble, ils aident une vieille dame à retrouver le souvenir de son fils disparu.', 31), 
 (246, 04, 'Les lettres effacées', 'Une boîte de lettres mouillées révèle un amour perdu entre deux lycéennes d’un autre temps.', 31), 
 (247, 05, 'Un orage sans nom', 'Un Écho devient violent, Aoi comprend qu’ils peuvent aussi être dangereux.', 31), 
 (248, 06, 'Kaede ne se souvient pas', 'Kaede montre des signes d’instabilité. Il pourrait être un Écho… ou autre chose.', 31), 
 (249, 07, 'La pluie refuse de s’arrêter', 'Une journée entière de pluie bloque la ville, les Échos deviennent plus nombreux.', 31), 
 (250, 08, 'Les parapluies abandonnés', 'Aoi découvre un sanctuaire secret lié à ceux qui entendent la pluie.', 31), 
 (251, 01, 'Avant que je m’efface', 'Aoi entre dans le souvenir de Kaede pour comprendre qui il est vraiment.', 32), 
 (252, 02, 'Le jour où la pluie s’est arrêtée', 'Retour 17 ans plus tôt : découverte de l’accident et du pacte entre deux enfants.', 32), 
 (253, 03, 'Le chant des flaques d’eau', 'Les Échos ne sont pas nés de la pluie… mais du silence des vivants.', 32), 
 (254, 04, 'Les jours de Kaede', 'Flashbacks sur la vie de Kaede, sa sœur, et l’origine de sa mémoire brisée.', 32), 
 (255, 05, 'Les gouttes que j’ai promises', 'Aoi découvre qu’elle était présente ce jour-là… avant même de naître.', 32), 
 (256, 06, 'Ce que l’on oublie', 'L’esprit d’un ancien Écho tente d’effacer tous les souvenirs liés à Kaede.', 32), 
 (257, 07, 'Ne me laisse pas sécher', 'Dernier lien émotionnel entre Aoi et Kaede — confession, choix, acceptation.', 32), 
 (258, 08, 'La dernière pluie', 'Aoi entend la pluie une dernière fois. Les Échos disparaissent. Kaede sourit.', 32), 
 (259, 01, 'Une boîte sous les fleurs', 'Hana découvre les lettres dans la vieille bibliothèque. Le mot “rencontre” est souligné à l’encre effacée.', 33), 
 (260, 02, 'Ren n’existe pas', 'Hana rencontre un garçon qu’aucun autre élève ne voit. Il lui dit qu’il ne reste que “jusqu’à la dernière floraison”.', 33), 
 (261, 03, 'Le banc du souvenir', 'Ensemble, ils retrouvent un lieu décrit dans la lettre 3. Hana commence à ressentir une douce nostalgie.', 33), 
 (262, 04, 'L’averse de pétales', 'Une pluie de cerisiers dévoile un souvenir que Hana n’a jamais eu : son premier amour.', 33), 
 (263, 05, 'Tu as oublié mon nom', 'Ren devient flou. Hana oublie un de leurs moments vécus la veille.', 33), 
 (264, 06, 'Entre les lignes', 'Hana commence à écrire ses propres lettres, dans l’espoir de changer quelque chose.', 33), 
 (265, 07, 'Ce que j’aurais voulu dire', 'Elle lit une lettre adressée… à Ren. Signée de son écriture.', 33), 
 (266, 08, 'Le jour où tout s’efface', 'Ren disparaît un matin. Les lettres s’effritent. Seul subsiste un haïku.', 33), 
 (267, 09, 'Hanami', 'Hana assiste seule à la fête des cerisiers. Elle entend sa voix une dernière fois dans le vent.', 33), 
 (268, 10, 'Je me souviendrai de t’oublier', 'Elle écrit une dernière lettre à elle-même. Puis continue sa vie, avec un sourire et une larme.', 33), 
 (269, 01, 'L’enfant du vent mort', 'Kazen, voleur dans une ville portuaire, survit grâce à son intuition surnaturelle. Lorsqu’il vole un artefact élémentaire, il déclenche une tempête incontrôlable qui attire l’attention des Liés.', 34), 
 (270, 02, 'Le cercle des sept', 'Le Conseil des Fils de l’Origine débat : Kazen n’a pas de lignée, mais peut invoquer les forces de plusieurs éléments. Il est jugé dangereux, et certains veulent l’exécuter.', 34), 
 (271, 03, 'La voix du magma', 'Fuyant le Conseil, Kazen se réfugie dans les montagnes du Feu, où il rencontre Myra, une Liée au tempérament explosif, qui décide de le former malgré les interdits.', 34), 
 (272, 04, 'Cristaux brisés', 'Un sanctuaire élémentaire est détruit. L’équilibre entre les éléments vacille. Kazen voit en rêve un huitième élément oublié, que personne ne reconnaît : le Néant.', 34), 
 (273, 05, 'La mémoire du sable', 'Kazen découvre un ancien manuscrit parlant d’un “Huitième Fils” né à chaque effondrement de cycle. Myra commence à douter de la version officielle du Conseil.', 34),
 (274, 06, 'Le pacte interdit', 'Pour éviter une guerre entre les lignées, le Conseil organise un tournoi où Kazen devra affronter les autres Liés. En secret, certains prévoient de le faire assassiner.', 34), 
 (275, 07, 'Les chaînes de givre', 'Capturé par la lignée de Glace, Kazen est torturé pour révéler son “véritable élément”. Il parvient à fusionner temporairement deux forces : Glace et Ombre.', 34), 
 (276, 08, 'L’éclat des cendres', 'Myra vient à son secours. Le lien entre eux s’approfondit. Ils découvrent un ancien temple souterrain gardé par des spectres de Liés oubliés.', 34), 
 (277, 09, 'Le huitième trône', 'Kazen y découvre un trône de pierre noire — symbole du Néant. En le touchant, il voit le monde tel qu’il était avant les éléments : pur chaos.', 34), 
 (278, 10, 'L’enfant que le monde a refusé', 'Revenu du temple, Kazen affronte le Conseil. Il n’est ni un Fils de l’Origine… ni un ennemi. Il est une anomalie. Et chaque anomalie, dans ce monde, annonce une révolution.', 34), 
 (279, 01, 'Les enfants sans lumière', 'Dans une région où plus aucun élément ne répond, Kazen rencontre des enfants nés “vides” : incapables de ressentir la magie. Il découvre qu’ils l’entendent en rêve.', 35), 
 (280, 02, 'Le miroir des sept', 'Myra découvre dans une bibliothèque souterraine un miroir ancien capable de refléter le “vrai lien” d’un individu. En l’utilisant sur Kazen, le miroir se brise… et montre une silhouette sans visage.', 35), 
 (281, 03, 'Le tombeau du premier feu', 'Guidés par une énigme, Kazen et ses compagnons trouvent le lieu de repos du tout premier Lié du Feu. Là, ils apprennent que les lignées sont issues d’un scellement collectif du Néant.', 35), 
 (282, 04, 'Le serment d’éclipse', 'Un groupe dissident de Liés, appelé l’Éclipse, offre à Kazen de rejoindre leur cause : détruire toutes les lignées et rétablir l’énergie originelle du monde. Kazen hésite.', 35), 
 (283, 05, 'Ce que l’on oublie', 'Kazen revoit en rêve des souvenirs qui ne sont pas les siens : d’anciens Huitièmes Fils, morts jeunes, toujours isolés ou trahis. L’un d’eux semble encore vivant quelque part.', 35), 
 (284, 06, 'Le gardien du néant', 'Dans les ruines d’un sanctuaire oublié, Kazen rencontre un homme masqué qui contrôle parfaitement le Néant. Il se nomme Auron, et se dit être son “ombre jumelle”.', 35), 
 (285, 07, 'Une guerre en silence', 'Auron révèle que le monde est pris dans une boucle : chaque cycle élémentaire engendre un porteur du Néant, et chaque fois, il est effacé. Kazen est le premier à survivre aussi longtemps.', 35), 
 (286, 08, 'Le sang des origines', 'Myra découvre que les fondateurs des lignées ont volontairement sacrifié un être du Néant pour “stabiliser” le monde. Kazen est leur lointain descendant, une anomalie biologique.', 35), 
 (287, 09, 'La fin du souffle', 'Alors que les éléments s’effondrent un à un (le feu ne brûle plus, l’eau reste figée, la terre se désagrège), Kazen fusionne totalement avec son pouvoir. Le monde entre dans une accalmie effrayante.', 35), 
 (288, 10, 'Ce que je choisis d’être', 'Kazen fait face au Conseil restauré. Il refuse l’héritage des lignées. Plutôt que de détruire les éléments ou de les dominer, il décide de se retirer avec Auron, emportant le Néant loin du monde. L’équilibre revient... mais différemment. Les lignées doivent renaître sans dogme.', 35), 
 (289, 01, 'Nuit sans fin', 'Kaito, adolescent rebelle, survit à une attaque d’une créature de la Veine. Il découvre qu’il est lui-même marqué.', 36), 
 (290, 02, 'Sang noir', 'Les premiers symptômes de la Veine apparaissent. Kaito rencontre Ayumi, une hackeuse qui cherche à percer le mystère.', 36), 
 (291, 03, 'Cicatrices visibles', 'Kaito lutte pour cacher ses transformations. Une organisation secrète, les Veilleurs, commence à le traquer.', 36), 
 (292, 04, 'Les murmures des ombres', 'Des hallucinations et visions terrifiantes tourmentent Kaito. Il découvre l’existence d’un ancien rituel lié à la Veine.', 36), 
 (293, 05, 'Le pacte du sang', 'Pour sauver un ami, Kaito accepte un dangereux pacte avec une entité obscure.', 36), 
 (294, 06, 'Fissures dans la nuit', 'La ville montre des signes de décomposition. Kaito affronte ses premières créatures transformées.', 36), 
 (295, 07, 'Trahison à Nocturna', 'Un membre des Veilleurs trahit le groupe, révélant des secrets sur l’origine de la Veine.', 36), 
 (296, 08, 'L’ombre du réveil', 'Kaito doit choisir entre son humanité et son pouvoir pour stopper une invasion imminente.', 36), 
 (297, 01, 'Échos du passé', 'Kaito découvre que sa famille est liée à la première apparition de la Veine.', 37), 
 (298, 02, 'Le sanctuaire oublié', 'Une ancienne base souterraine cache des expériences menées sur la Veine.', 37), 
 (299, 03, 'Fragments de mémoire', 'Kaito perd le contrôle, et ses souvenirs se brouillent.', 37), 
 (300, 04, 'L’appel du néant', 'Une nouvelle faction rival émerge, exploitant la Veine pour ses propres desseins.', 37), 
 (301, 05, 'Les chaînes du sang', 'Kaito affronte ses ancêtres dans une dimension alternative.', 37), 
 (302, 06, 'La lame de l’aube', 'Ayumi révèle son propre passé lié à la malédiction.', 37), 
 (303, 07, 'Brèche dans l’ombre', 'Le voile entre monde réel et cauchemars s’efface.', 37), 
 (304, 08, 'Résonance fatale', 'Une bataille éclate pour le contrôle d’un artefact capable de purifier la Veine.', 37), 
 (305, 01, 'Courroux de la nuit', 'Nocturna est en état de siège par des hordes mutantes.', 38), 
 (306, 02, 'Le creuset des âmes', 'Kaito plonge dans un rituel risqué pour renforcer son pouvoir.', 38), 
 (307, 03, 'L’allié brisé', 'Un proche de Kaito est possédé par la Veine.', 38), 
 (308, 04, 'Masques de l’oubli', 'Une conspiration dans l’ombre menace la résistance.', 38), 
 (309, 05, 'Cendres de l’espoir', 'Kaito fait face à une perte dévastatrice.', 38), 
 (310, 06, 'L’arène des damnés', 'Combat mortel organisé par une faction ennemie.', 38), 
 (311, 07, 'Le sang du pacte', 'Kaito conclut un accord désespéré avec une force mystérieuse.', 38), 
 (312, 08, 'Crépuscule éternel', 'Une éclipse magique plonge la ville dans un chaos apocalyptique.', 38), 
 (313, 01, 'L’ultime veine', 'Kaito découvre la source originelle de la malédiction.', 39),
 (314, 02, 'Fractures du destin', 'Des alliances se brisent, et la confiance vacille.', 39), 
 (315, 03, 'Le prix du sang', 'Kaito doit faire un sacrifice pour obtenir un pouvoir final.', 39), 
 (316, 04, 'Rébellion des ombres', 'La résistance mène une offensive désespérée.', 39), 
 (317, 05, 'Le souffle de minuit', 'Kaito fait face à son double obscur dans un duel intérieur.', 39), 
 (318, 06, 'Les chaînes du passé', 'Secrets révélés, vérité douloureuse.', 39), 
 (319, 07, 'L’éclat de la dernière lune', 'La bataille finale commence sous une pleine lune rouge.', 39), 
 (320, 08, 'Veine éternelle', 'Résolution du conflit, avec un épilogue qui laisse place à une possible suite.', 39), 
 (321, 01, 'Décharge initiale', 'Riku s’engage dans une course illégale et découvre par hasard un ancien Circuit capable d’augmenter sa vitesse.', 40), 
 (322, 02, 'Rivalité électrique', 'Il affronte Haru, un coureur talentueux et arrogant, et fait connaissance avec Ayane, une mécanicienne passionnée.', 40), 
 (323, 03, 'Sur la ligne de départ', 'Premiers entraînements intensifs. Riku apprend à canaliser son pouvoir et à comprendre les risques des implants.', 40), 
 (324, 04, 'Courants croisés', 'Un tournoi local attire de nouveaux challengers. Les rivalités se complexifient.', 40), 
 (325, 05, 'Foudre dans la nuit', 'Riku subit une défaillance de son Circuit en pleine course et doit faire preuve d’ingéniosité pour s’en sortir.', 40), 
 (326, 06, 'Pulse en fusion', 'Riku remporte une course importante, mais comprend que sa découverte attire aussi des regards dangereux.', 40), 
 (327, 01, 'Signal d’alarme', 'Riku découvre l’existence d’une organisation secrète qui étudie les Circuits anciens.', 41), 
 (328, 02, 'Choc des pulsars', 'Une compétition régionale oppose les meilleurs coureurs, dont un rival qui maîtrise un Circuit inédit.', 41), 
 (329, 03, 'Surcharge', 'Le Circuit de Riku montre des signes d’instabilité, mettant sa vie en danger.', 41), 
 (330, 04, 'Résonance', 'Ayane met au point une amélioration pour stabiliser le Circuit. Riku repousse ses limites.', 41), 
 (331, 05, 'Courant inverse', 'Un coureur mystérieux aux pouvoirs électromagnétiques défie Riku en duel.', 41), 
 (332, 06, 'Connexion finale', 'Riku gagne le tournoi, mais doit faire un choix important sur l’utilisation de ses pouvoirs.', 41), 
 (333, 01, 'Ligne rouge', 'Une nouvelle technologie menace de rendre les anciens Circuits obsolètes.', 42), 
 (334, 02, 'Décharge fatale', 'Une course extrême met Riku face à un défi mortel.', 42),
 (335, 03, 'Cœurs en circuit', 'Riku et Ayane affrontent ensemble une crise personnelle qui teste leur amitié.', 42), 
 (336, 04, 'Fréquence perdue', 'Riku se confronte à son passé et à la véritable origine des Circuits.', 42), 
 (337, 05, 'Éclair de vérité', 'Le secret derrière les Circuits anciens est dévoilé, bouleversant tout.', 42), 
 (338, 06, 'Pulse éternel', 'Dernière course décisive où Riku doit choisir entre puissance et humanité.', 42), 
 (339, 01, 'L’Éveil Incomplet', 'Kael se réveille dans les ruines de Vasterra, sans mémoire, en proie à des visions de combats passés. Il est attaqué par des soldats de la faction Nullex, mais sauvé in extremis par Ayra. Elle lui révèle qu’il porte une marque interdite, symbole du Rebirth Protocol.', 43), 
 (340, 02, 'La Marque et le Masque', 'Kael tente de comprendre sa marque pendant que Ayra l’emmène dans un sanctuaire caché. Il est confronté à un miroir du passé, qui lui montre une version ancienne de lui-même. Une première manifestation incontrôlée de ses pouvoirs détruit le sanctuaire.', 43), 
 (341, 03, 'Flux Déchaîné', 'Sous l’emprise d’un pouvoir qu’il ne contrôle pas, Kael met en danger Ayra. Un mage mécanique, Milo, neutralise Kael avec une magie anti-protocolaire. Le trio se met en route vers le bastion rebelle de Cindra.', 43), 
 (342, 04, 'Les Fragments du Soi', 'Grâce à un artefact mémoire, Kael accède à un souvenir d’une ancienne vie : il était un guerrier nommé "Rhen", protecteur du monde. Il comprend qu’il n’en est pas à sa première renaissance. Mais un mystérieux individu, "le Scribe", observe son évolution.', 43), 
 (343, 05, 'Le Pacte de Cendres', 'À Cindra, Kael doit passer une épreuve d’initiation magique pour gagner la confiance des rebelles. Il affronte une entité issue de son subconscient et réussit à en extraire une nouvelle capacité : la lame du cycle.', 43), 
 (344, 06, 'Les Éveillés Sont Parmi Nous', 'Un des chefs rebelles est tué par un infiltré Éveillé. L’équipe découvre que plusieurs incarnations précédentes de Kael ont sombré et se sont alliées à l’ennemi. Le doute s’installe : Kael est-il une menace en devenir ?', 43), 
 (345, 07, 'Cœur Résonant', 'Ayra révèle ses vraies motivations : elle est la descendante d’un ancien gardien trahi par une précédente version de Kael. Elle le teste dans une confrontation brutale. Leur lien se renforce, mêlant méfiance, douleur et respect.', 43), 
 (346, 08, 'Le Labyrinthe de l’Oubli', 'Milo conduit le groupe vers une zone ancestrale nommée "le Labyrinthe d’Éther", qui conserve tous les souvenirs perdus du Protocole. Kael y affronte des versions distordues de lui-même. Il en ressort plus fort, mais troublé.', 43), 
 (347, 09, 'Le Scribe', 'Le mystérieux observateur entre en scène. Il prétend être l’architecte du Rebirth Protocol, un gardien d’un autre temps. Il avertit Kael qu’un éveil total pourrait libérer Xarion, une entité chaotique enfermée dans le cycle depuis des millénaires.', 43), 
 (348, 10, 'Reboot', 'Kael choisit de briser un des sceaux du Rebirth Protocol pour sauver Ayra, au risque d’ouvrir une brèche. Ses pouvoirs s’éveillent pleinement pour la première fois. Mais un tremblement magique traverse le monde : les autres Éveillés se sont réveillés.', 43), 
 (349, 01, 'Fractures', 'La terre tremble. Des failles magiques apparaissent dans plusieurs régions. Kael, Ayra et Milo fuient Cindra, détruite lors du réveil des Éveillés. Ils croisent un premier Éveillé : Lüen, incarnation pacifique mais déstabilisée du passé de Kael. Elle l’avertit : "Ils ne veulent pas fusionner. Ils veulent dominer."', 44), 
 (350, 02, 'Les Trois Premiers', 'Les Éveillés sont au nombre de douze. Trois d’entre eux — Varn, le stratège ; Sahen, la mystique ; et Dreid, l’anarchiste — se sont réunis pour former la Triade. Leur objectif : briser définitivement le Protocole et s’affranchir de leur lien avec Kael.', 44), 
 (351, 03, 'La Cité Miroir', 'À la recherche d’un ancien sanctuaire, le trio arrive à Liorah, cité suspendue dans l’espace-temps, où vit Aenys, la mémoire vivante du Protocole. Elle révèle que Kael peut absorber ou libérer les Éveillés… mais chaque fusion affectera son esprit et son identité.', 44), 
 (352, 04, 'Reflet Rouge', 'Ayra est capturée par Dreid. Kael part à sa recherche et affronte une version d’un lui-même ultra-violent : Kael-Rouge, incarnation de la colère et de l’instinct brut. Le combat est intense, mais Kael réussit à le neutraliser et à l’absorber — une première fusion.', 44), 
 (353, 05, 'Entre Deux Mondes', 'L’absorption de Kael-Rouge perturbe l’équilibre mental de Kael, qui perd temporairement le contrôle. Ayra tente de le ramener à lui avec l’aide d’un artefact de mémoire. Kael voit alors les souvenirs de Rhen, Kellian et Tyre, trois anciennes vies.', 44), 
 (354, 06, 'Le Jugement de Sahen', 'La Triade lance une attaque contre un bastion des Gardiens du Protocole. Sahen y attend Kael pour un duel mystique. Plutôt que de combattre, elle cherche à tester sa stabilité. Impressionnée par son refus de la violence gratuite, elle quitte la Triade.', 44), 
 (355, 07, 'Le Sacrifice de Milo', 'Une attaque d’Éveillés corrompt l’Étincelle d’Éther de Milo, qui perd le contrôle de sa magie techno. Pour éviter un désastre, Milo déclenche un contrecoup sur lui-même, tombant dans un coma profond. Kael jure de le sauver en trouvant le Nexus Originel.', 44), 
 (356, 08, 'Le Temple Noir', 'Kael et Ayra entrent dans un ancien temple de l’époque des premiers Protocles. Ils y croisent Velka, une incarnation froide et calculatrice du passé de Kael. Elle propose une alliance temporaire, en échange de la promesse que Kael ne brisera jamais le cycle.', 44), 
 (357, 09, 'La Chute de la Triade', 'Varn et Dreid lancent une attaque massive sur les Hauts Lieux de Mirhal. Kael et Velka unissent leurs forces. Grâce à la fusion de Kael avec un deuxième Éveillé (Tyre), il terrasse Dreid. Varn s’échappe, mais la Triade est dissoute.', 44), 
 (358, 10, 'Échos du Premier', 'Kael reçoit un appel étrange dans ses rêves. Une voix oubliée, ancienne même parmi les Éveillés, l’interpelle : "Tu m’as banni, Kael. Je suis toi avant toi." Le Premier Éveillé, originel et incontrôlable, s’éveille dans les ruines de Reon. La saison se termine sur son œil s’ouvrant, noir comme le vide.', 44), 
 (359, 01, 'Corde sensible', 'Airi assiste par hasard à un atelier de musique improvisée. Le son du piano la fait pleurer malgré elle.', 45), 
 (360, 02, 'Le garçon du silence', 'Elle entend pour la première fois le jeu de Hiro, violoncelliste distant mais captivant. Il semble reconnaître son violon.', 45), 
 (361, 03, 'Fausse note', 'Riku, joyeux et envahissant, tente de convaincre Airi de rejoindre l’atelier. Elle refuse… puis revient en secret.', 45), 
 (362, 04, 'Partition blanche', 'Airi joue en public pour la première fois depuis trois ans. Sa main tremble, mais elle ne s’arrête pas.', 45), 
 (363, 05, 'Dissonance', 'Une dispute éclate entre Riku et Hiro, qui interprètent différemment une pièce qu’Airi a commencée.', 45), 
 (364, 06, 'Le son d’avant', 'Flashback sur le frère d’Airi, et la nuit de l’accident. Une vieille cassette refait surface.', 45), 
 (365, 07, 'Crescendo', 'Airi compose une œuvre à trois mains. Elle commence à accepter qu’elle ne joue pas que pour le passé.', 45), 
 (366, 08, 'Tension', 'Hiro s’éloigne brusquement après un baiser volé. Riku prend le relais, maladroit mais sincère.', 45), 
 (367, 09, 'Dernière répétition', 'Les trois se retrouvent une nuit sur le toit pour une session sous les étoiles. Ils rejouent tout ce qu’ils n’ont pas dit.', 45), 
 (368, 10, 'En harmonie', 'Airi monte sur scène seule, interprétant leur composition. Dans la salle, deux regards croisés… et une note suspendue.', 45);

-- Insertion des anime_type
INSERT INTO Anime_type (type_id, anime_id) VALUES
(4, 1), (1, 1), (3, 1),
(4, 2), (1, 2),
(2, 3), (3, 3), (4, 3),
(3, 4), (4, 4),
(4, 5), (9, 5),
(2, 6), (3, 6), (4, 6),
(2, 7), (6, 7),
(4, 8), (9, 8),
(3, 9), (4, 9),
(9, 10), (4, 10),
(8, 11), (6, 11), (4, 11),
(8, 12), (4, 12), (6, 12),
(6, 13), (4, 13), (8, 13),
(6, 14), (4, 14), (8, 14), (1, 14),
(6, 15), (4, 15), (8, 15), (1, 15),
(1, 16), (3, 16),
(2, 17), (9, 17),
(3, 18), (4, 18), (5, 18), (8, 18),
(1, 19), (4, 19), (3, 19),
(6, 20), (4, 20), (8, 20);